--- #YAML:1.0
name: Math-Random-MT-Perl
version: 1.05
abstract: Pure Perl Mersenne Twister Random Number Generator
license: artistic_2
generated_by: ExtUtils::MakeMaker version 6.3201
distribution_type: module
requires:     
  perl: 5.0
provides:
  Math::Random::MT::Perl:
    file: lib/Math/Random/MT/Perl.pm
    version: 1.05
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
author:
  - Dr James Freeman
